name: "🐞 Bug Report"
description: "Help us identify and fix bugs in the project by providing detailed reports."
title: "Bug Report: "
labels: ["bug", "help wanted"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve! Please provide detailed information about the bug you encountered. This ensures we can address it efficiently.
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "🔖 Bug Description"
      description: "Provide a clear and concise description of the bug, including what you expected to happen and what actually happened."
      placeholder: "Describe the bug here..."
  - type: textarea
    id: evidence
    attributes:
      label: "📷 Screenshot or Video (Optional)"
      description: "If possible, attach screenshots or videos to demonstrate the bug."
      placeholder: "Link or attach visual evidence."
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: "✔️ Checklist"
      options:
        - label: "I have searched existing issues to ensure this is not a duplicate."
          required: true
        - label: "I have read and followed the [Contributing Guidelines](CONTRIBUTING.md)."
          required: true
        - label: "I have read and agree to the [Code of Conduct](CODE_OF_CONDUCT.md)."
          required: true
        - label: "I am willing to work on this issue."
          required: false
  - type: textarea
    id: additional-notes
    attributes:
      label: "📝 Additional Notes (Optional)"
      description: "Provide any extra context or relevant information about the bug."
      placeholder: "Add additional details here..."
    validations:
      required: false
